function scanHTML(c){const ch=c.exactCheck;return `<div class="notice amber"><strong>已完成零错配扫描；仍未完成近似匹配与实验验证。</strong><div class="hint">${esc(ch.warning)}</div></div><div class="table-wrap"><table><thead><tr><th>引物</th><th>完整序列精确命中</th><th>已保存位置</th></tr></thead><tbody>${ch.results.map(x=>`<tr><td class="mono">${esc(x.id)}</td><td>${x.totalHits}</td><td>${x.hits.length}${x.positionsTruncated?'（截断）':''}</td></tr>`).join('')}</tbody></table></div><div class="hint" style="margin-top:8px">精确配对产物（上传参考，40–3000 bp）：${(c.exactProducts||[]).map(x=>esc(x.name)+' '+x.result.count+(x.result.truncated?'（位置截断，仅下界）':'')).join('；')}。KASP ALT 在 REF 基因组无产物不意味着其在 ALT 样本不扩增。详见完整 JSON。</div>`;}
function renderResults(){const count=results.reduce((s,r)=>s+(r.candidates?.length||0),0);$('resultCount').textContent=count;document.querySelectorAll('.export-btn').forEach(x=>x.disabled=!results.length);if(!results.length){$('resultContent').innerHTML='<div class="empty"><strong>暂无已完成结果</strong><p>取消状态及结果边界不会被转换为成功状态。</p></div>';return;}
 $('resultContent').innerHTML=results.map((r,i)=>`<div class="result-locus"><div class="locus-top"><h3>${esc(r.context.id||'target')} <span class="smallmeta">${esc(r.context.ref)} → ${esc(r.context.alt)}</span></h3><span class="pill">${r.candidates.length} 组候选</span></div>${r.context.geneHits?.length?`<div class="gene-hit"><strong>MSU GFF3 overlap:</strong> ${r.context.geneHits.map(g=>esc(g.id)).join('；')}<div class="hint">${esc(compactFeatureLabel(r.context.featureContext||[]))} · 仅 genomic/transcript 结构定位，不替代 consequence annotation。</div>${variantStructureHTML(r.context,r.context.featureContext||[])}</div>`:''}${r.error?`<div class="notice error">${esc(r.error)}</div>`:`<div class="result-note">${r.context.source==='LOCAL_REFERENCE'?'本地参考 · '+esc(r.context.chrom)+':'+r.context.pos:r.context.source?.includes('SYNTHETIC')?'固定种子合成示例 · 非 MSU · 非真实位点':'用户侧翼序列 · 来源未认证'} · REF 已与输入窗口一致性核对</div>${rescueHTML(r)}${!r.candidates.length?'<div class="noresult">本次参数与 Auto-rescue 范围内未找到候选。这不表示位点不可设计；请核查侧翼、模板质量与参数，不自动降低筛选标准。</div>':''}${r.candidates.map((c,j)=>cardHTML(r,c,i,j)).join('')}<details style="margin:12px 0"><summary>诊断与未完成检查</summary><div class="meta">${esc(JSON.stringify(r.diagnostics,null,2))}</div><div class="notice amber">${(r.warnings||[]).map(esc).join('<br>')}</div></details>`}</div>`).join('');
 $('resultContent').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyCandidate(Number(b.dataset.row),Number(b.dataset.copy)));$('resultContent').querySelectorAll('[data-scan]').forEach(b=>b.onclick=()=>scanCandidate(Number(b.dataset.row),Number(b.dataset.scan)));}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制。');}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'已复制。':'浏览器限制复制，请导出 FASTA 或 CSV。');}}
function copyCandidate(ri,ci){const r=results[ri],c=r.candidates[ci];copyText(c.primers.map(p=>`${r.context.id}_C${ci+1}_${p.role}\t${p.sequence}\t${c.status}`).join('\n'));}
async function scanCandidate(ri,ci){if(busy)return;const r=results[ri],c=r.candidates[ci];if(!refFile||r.refRevision!==refRevision||r.context.source!=='LOCAL_REFERENCE'){toast('参考已改变或来源并非本地参考，请重新设计。');return;}cancelRequested=false;clearError();setBusy(true);try{const check=await runWorker('scan',{file:refFile,queries:c.primers.map(o=>({id:o.role,sequence:o.core}))},p=>showProgress(`全基因组零错配扫描 · ${(100*p).toFixed(0)}%`,p));c.exactCheck=check;const by=Object.fromEntries(check.results.map(x=>[x.id,x]));c.exactProducts=c.mode==='sanger'?[{name:'F/R',result:RPSIO.exactProducts(by.F,by.R)}]:['REF','ALT'].map(x=>({name:'AS_'+x+'/COMMON',result:RPSIO.exactProducts(by['AS_'+x],by.COMMON)}));c.exactCheck.reference=refMeta();c.exactCheck.completedAt=new Date().toISOString();renderResults();toast('精确匹配完成；这不是特异性通过判定。');}catch(e){if(!cancelRequested)error(e.message);}finally{setBusy(false);}}
const columns=['target_id','mode','candidate','status','reference_file','reference_sha256','template_sha256','gene_overlap','feature_region','nearest_donor_boundary_bp','nearest_acceptor_boundary_bp','splice_motif_check','splice_motif_overlap','splice_nearby_noncanonical','gff_file','gff_sha256','chrom','pos_1based','ref','alt','role','allele','channel','direction','core_5to3','tail_5to3','full_sequence_5to3','length_core','length_full','tm_core_C','gc_core_pct','product_ref_bp','product_alt_bp','reference_start_1based','reference_end_1based','self_3prime_contiguous_nt','hairpin_stem_nt','exact_hit_count','approximate_offtarget','wetlab','algorithm','version'];
function csvCell(v){let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCsv(){const rows=[columns];for(const r of results)for(let i=0;i<r.candidates.length;i++){const c=r.candidates[i];for(const o of c.primers){const x=c.exactCheck?.results.find(x=>x.id===o.role);rows.push([r.context.id,r.mode,i+1,isSyntheticResult(r)?'SYNTHETIC_NOT_FOR_ORDER':c.status,r.reference?.filename,r.reference?.sha256,r.context.templateSha256,(r.context.geneHits||[]).map(g=>g.id).join(';'),compactFeatureLabel(r.context.featureContext||[]),nearestBoundarySummary(r.context.featureContext||[],'nearest_donor_boundary')?.distance_bp??'NA',nearestBoundarySummary(r.context.featureContext||[],'nearest_acceptor_boundary')?.distance_bp??'NA',r.context.spliceMotifAudit?.status||'NOT_RUN',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.variant_overlaps_any_motif?'YES':'NO'):'NOT_ASSESSED',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.noncanonical_nearby?'YES':'NO'):'NOT_ASSESSED',r.context?.annotationAudit?.gff?.filename||r.reference?.gff?.filename||'',r.context?.annotationAudit?.gff?.sha256||r.reference?.gff?.sha256||'',r.context.chrom,r.context.pos,r.context.ref,r.context.alt,o.role,o.allele,o.channel,o.strand,o.core,o.tail,o.sequence,o.length,o.fullLength,o.tm.toFixed(4),o.gc.toFixed(4),c.productRef,c.productAlt,o.genomicStart1,o.genomicEnd1,o.selfEnd,o.hairpin,x?.totalHits??'NOT_RUN','NOT_RUN','NOT_VALIDATED',r.algorithm,r.version]);}}save('rice_primer_candidates.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function exportFasta(){const lines=[];for(const r of results)for(let i=0;i<r.candidates.length;i++)for(const o of r.candidates[i].primers)lines.push(`>${String(r.context.id).replace(/[^A-Za-z0-9_.-]/g,'_')}_C${i+1}_${o.role} source=${r.context.source} status=NOT_VALIDATED channel=${o.channel||'NA'}`,o.sequence);save('rice_primer_candidates.fasta',lines.join('\n')+'\n');}
function exportJson(){save('rice_primer_run_v1.1.0-rc4.3.json',JSON.stringify({schemaVersion:'rps.run/2',manifest:runManifest,exportedAt:new Date().toISOString(),results},null,2),'application/json;charset=utf-8');}

function isSyntheticResult(r){return Boolean(r.context.source?.includes('SYNTHETIC')||r.reference?.filename?.startsWith('SYNTHETIC_'));}
function nativeOrigin(){return document.querySelector('meta[name="rps-deployment"]')?.content!=='PUBLIC_STATIC'&& ['127.0.0.1','localhost'].includes(location.hostname)&&location.protocol==='http:';}
async function checkBackend(){
 if(!nativeOrigin()){toast('请在源码包目录运行 python3 backend/server.py，再从 http://127.0.0.1:8765/ 打开。双击 HTML 仍可使用离线模式。');return;}
 $('checkBackend').disabled=true;try{const res=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!res.ok)throw Error('本机服务未返回健康状态。');nativeInfo=await res.json();
 if(nativeInfo.appVersion!==RPS.VERSION)throw Error('本机服务与网页版本不一致。');
 $('engineStatus').textContent=nativeInfo.primer3Available?`本机检测到 primer3-py ${nativeInfo.primer3PyVersion}。本发布包未对原生数值分支完成验收；序列只传给本机服务。`:`本机服务可用，但需要 primer3-py ${nativeInfo.requiredVersion}；当前 ${nativeInfo.primer3PyVersion||'未安装'}。原生模式不会静默回退。`;
 }catch(e){nativeInfo=null;$('engineStatus').textContent='本机检查失败：'+e.message;}finally{$('checkBackend').disabled=false;}
}
async function nativeCall(path,payload){
 if(!nativeOrigin())throw Error('原生引擎仅支持配套本机服务，不接受远程服务器地址。');
 const token=document.querySelector('meta[name="rps-native-token"]')?.content;if(!token)throw Error('当前页面不是由配套服务生成，缺少本机会话令牌。');
 nativeAbort=new AbortController();try{const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-RPS-Token':token},body:JSON.stringify(payload),signal:nativeAbort.signal,cache:'no-store'});const obj=await res.json();if(!res.ok)throw Error(obj.error||'本机计算失败。');return obj;}finally{nativeAbort=null;}
}
async function designWithEngine(c,m,p,choice){
 if(choice==='offline')return runWorker('design',{context:c,mode:m,params:p});
 if(m==='sanger')return nativeCall('/api/design',{context:c,mode:m,params:p});
 const r=await runWorker('design',{context:c,mode:m,params:p});
 for(const candidate of r.candidates){if(cancelRequested)throw Error('任务已取消。');candidate.thermoCheck=await nativeCall('/api/thermo',{params:p,oligos:candidate.primers.map(o=>({role:o.role,core:o.core,sequence:o.sequence}))});}
 r.algorithm='RPS_ENUMERATION_PLUS_PRIMER3_THERMO_REVIEW_v1';r.warnings.push('KASP 仍由离线枚举产生；Primer3 仅补充热力学数值复核，不是原生 KASP 设计算法，未自动根据 ΔG 放行。');return r;
}
function selectedCount(){return results.reduce((n,r)=>n+r.candidates.filter(c=>c.selected).length,0);}
function updateSummary(){const n=selectedCount(),done=results.filter(r=>!r.error&&r.candidates.length).length,empty=results.filter(r=>!r.error&&!r.candidates.length).length,failed=results.filter(r=>r.error).length;
 $('selectedCsv').textContent=`选中组 CSV · ${n}`;$('selectedCsv').disabled=busy||n===0;
 $('outputSummary').classList.toggle('hidden',results.length===0);$('outputSummary').innerHTML=`<span><strong>${results.length}</strong> 个已完成位点 · ${done} 有候选 · ${empty} 无候选 · ${failed} 错误</span><span>已选 ${n} 组 · 仅用于复核${runManifest?.cancelled?' · 本次运行已取消':''}</span>`;
}
function qualityHTML(r,c){const audit=RPSAudit.candidateIntegrity(r,c);const b=r.inputContext?.backgroundAudit;return `<div class="qualitystrip"><span class="qualityitem">候选一致性 ${audit.status}</span><span class="qualityitem">REF 一致性已核对</span><span class="qualityitem">${b?.status&&b.status!=='NOT_PROVIDED'?'已应用所供背景清单':'背景变异未提供'}${b?.maskedIntervals?' · '+b.maskedIntervals+' 段排除':''}</span><span class="qualityitem">${r.inputContext?.repeatAudit?.status==='PROVIDED'?'Repeat 注释已应用 · '+r.inputContext.repeatAudit.localIntervals+' 段':'Repeat 注释未提供'}</span><span class="qualityitem">${c.approxCheck?'已扫描 ≤'+c.approxCheck.mismatchesAllowed+' 处替换':'近似匹配未运行'}</span><span class="qualityitem">${c.thermoCheck?'已取得 Primer3 热力学数值':'热力学 ΔG 未运行'}</span><span class="qualityitem">实验未验证</span></div>`;}
function ampliconHTML(r,c){try{const a=RPSReview.amplicons(r.inputContext,c);function content(seq,target,allele){return Number.isInteger(target)?esc(seq.slice(0,target))+`<span class="allele-mark">${esc(seq.slice(target,target+allele.length))}</span>`+esc(seq.slice(target+allele.length)):esc(seq);}
 return `<details style="margin:14px 0"><summary>查看 REF / ALT 扩增子 · 不含尾序</summary><div class="hint">REF/ALT 扩增子 GC ${fmt(c.ampliconAudit?.ref?.gc,1)}% / ${fmt(c.ampliconAudit?.alt?.gc,1)}%；最高完整 50 bp 窗口 GC ${fmt(c.ampliconAudit?.ref?.peak50?.gc,1)}% / ${fmt(c.ampliconAudit?.alt?.peak50?.gc,1)}%。${c.ampliconAudit?.readReach?'测序可达性：'+esc(c.ampliconAudit.readReach.status)+'（用户规划 '+c.ampliconAudit.readReach.planningLimitBp+' bp，非实测读长）。':''}</div><div class="hint">${a.orientation==='+'?'按参考正向':'按反向互补方向'}显示；KASP 两条 AS 引物长度不同也会改变产物长度，不能将产物差直接解释为 InDel 长度。</div><div class="amp-head">REF · ${a.ref.length} bp</div><pre class="amplicon">${content(a.ref,a.targetRef0,r.inputContext.ref)}</pre><div class="amp-head">ALT · ${a.alt.length} bp</div><pre class="amplicon">${content(a.alt,a.targetAlt0,r.inputContext.alt)}</pre></details>`;
 }catch(e){return `<div class="notice error">扩增子复核失败：${esc(e.message)}</div>`;}
}
const fmt=(v,d=2)=>Number.isFinite(v)?v.toFixed(d):'—';
function thermoHTML(c){if(!c.thermoCheck)return '';const t=c.thermoCheck;return `<details style="margin:12px 0"><summary>Primer3 热力学复核 · ${esc(t.primer3PyVersion)}</summary><div class="hint">ΔG 温度 ${esc(t.parameters?.temp_c)}°C；结构分析包括尾序。这里没有实验通过判定；结合区 Tm 数值使用 Primer3 的明确条件。</div><div class="table-wrap"><table><thead><tr><th>引物</th><th>结合区 Tm / °C</th><th>发卡 ΔG / kcal·mol⁻¹</th><th>同源二聚体 ΔG</th></tr></thead><tbody>${(t.oligos||[]).map(o=>`<tr><td>${esc(o.role)}</td><td>${fmt(o.tmCoreC)}</td><td>${fmt(o.hairpin?.dgKcalMol)}</td><td>${fmt(o.homodimer?.dgKcalMol)}</td></tr>`).join('')}</tbody></table></div><div class="hint">异源二聚体：${(t.pairs||[]).map(o=>esc(o.a)+'/'+esc(o.b)+' '+fmt(o.heterodimer?.dgKcalMol)+' kcal/mol').join('；')}。两种方向的 3′ 端稳定性与原始 cal/mol 数值见完整 JSON。</div></details>`;}
function approxHTML(c){if(!c.approxCheck)return '';const q=c.approxCheck;return `<div class="notice amber"><strong>已扫描完整结合区 ≤${q.mismatchesAllowed} 处替换；不是特异性通过。</strong><div class="hint">${esc(q.warning)}</div></div><div class="table-wrap"><table><thead><tr><th>引物</th><th>总命中</th><th>按错配数计数</th><th>位置保存</th></tr></thead><tbody>${q.results.map(x=>`<tr><td>${esc(x.id)}</td><td>${x.totalHits}</td><td>${x.byMismatches.map((n,i)=>`${i} 处: ${n}`).join(' / ')}</td><td>${x.hits.length}${x.positionsTruncated?' · 已截断':''}</td></tr>`).join('')}</tbody></table></div><div class="hint" style="margin:7px 0">扫描 ${q.contigsScanned} 个 contig，${q.basesScanned.toLocaleString()} bp；参考含 ${q.ambiguousBases.toLocaleString()} 个模糊碱基。配对产物范围 40–3000 bp：${(c.approxProducts||[]).map(x=>esc(x.name)+' '+x.result.count+(x.result.truncated?'（下界）':'')).join('；')}。所有命中均显示，不自动将目标位点交叉等位命中归为脱靶。</div><details><summary>查看部分命中坐标和 3′ 错配</summary><div class="table-wrap"><table><thead><tr><th>引物</th><th>位置 · 1-based</th><th>链</th><th>距 3′ 端第几位</th></tr></thead><tbody>${q.results.flatMap(x=>x.hits.slice(0,8).map(h=>`<tr><td>${esc(x.id)}</td><td>${esc(h.chrom)}:${h.start0+1}–${h.end0}</td><td>${h.strand}</td><td>${h.mismatchFrom3prime1.join(', ')||'零错配'}</td></tr>`)).join('')}</tbody></table></div><div class="hint">每条引物此处最多展示 8 个位置；全部已保存位置见 JSON。位置截断时，不允许据此作“无其他产物”的结论。</div></details>`;}
const baseCardHTML=cardHTML;
cardHTML=function(r,c,ri,ci){let html=baseCardHTML(r,c,ri,ci);const allowed=refFile&&r.refRevision===refRevision&&r.context.source==='LOCAL_REFERENCE';
 html=html.replace('<div class="metrics">',(ci===0?locusQualityHTML(r):'')+qualityHTML(r,c)+'<div class="metrics">');
 html=html.replace('<div id="scan-',ampliconHTML(r,c)+thermoHTML(c)+`<div class="approx-result">${approxHTML(c)}</div><div id="scan-`);
 html=html.replace('<div class="card-actions">',`<div class="card-actions"><label class="reviewselect"><input type="checkbox" data-select="${ci}" data-row="${ri}" ${c.selected?'checked':''} ${busy?'disabled':''}>选入复核清单</label>`);
 html=html.replace('<button class="btn small" data-scan=',`<button class="btn small" data-approx="${ci}" data-row="${ri}" ${!allowed||busy?'disabled':''}>扫描 0–2 处替换</button><button class="btn small" data-scan=`);
 return html;
};
const baseRenderResults=renderResults;
renderResults=function(){baseRenderResults();updateSummary();
 $('resultContent').querySelectorAll('[data-select]').forEach(b=>b.onchange=()=>{const r=results[Number(b.dataset.row)];r.candidates.forEach((c,i)=>c.selected=i===Number(b.dataset.select)&&b.checked);renderResults();});
 $('resultContent').querySelectorAll('[data-approx]').forEach(b=>b.onclick=()=>scanApproxCandidate(Number(b.dataset.row),Number(b.dataset.approx)));
};
const baseSetBusy=setBusy;
setBusy=function(v){baseSetBusy(v);document.querySelectorAll('[data-approx]').forEach(b=>b.disabled=v||!refFile||results[Number(b.dataset.row)]?.refRevision!==refRevision||results[Number(b.dataset.row)]?.context.source!=='LOCAL_REFERENCE');document.querySelectorAll('.export-btn').forEach(b=>b.disabled=v||!results.length);$('importRun').disabled=v;$('exportDecision').disabled=v||!results.length;$('autoSelectPreferred').disabled=v||!results.some(r=>r.candidates?.length);for(const id of ['exportSangerOrder','exportKaspOrder','exportQcRelease','exportAuditManifest'])$(id).disabled=v||!results.length;updateSummary();};
async function scanApproxCandidate(ri,ci){if(busy)return;const r=results[ri],c=r.candidates[ci];if(!refFile||r.refRevision!==refRevision||r.context.source!=='LOCAL_REFERENCE')return;
 const maxMismatches=Number($('scanMismatches').value);cancelRequested=false;clearError();setBusy(true);
 try{const check=await runWorker('approx',{file:refFile,queries:c.primers.map(o=>({id:o.role,sequence:o.core})),maxMismatches},p=>showProgress(`完整结合区 ≤${maxMismatches} 处替换 · ${(100*p).toFixed(0)}%`,p));if(cancelRequested)return;
 c.approxCheck={...check,reference:refMeta(),completedAt:new Date().toISOString()};const by=Object.fromEntries(check.results.map(x=>[x.id,x]));const pairs=c.mode==='sanger'?[['F','R']]:[['AS_REF','COMMON'],['AS_ALT','COMMON']];
 c.approxProducts=pairs.map(([a,b])=>{const result=RPSIO.exactProducts(by[a],by[b]);result.scope='UPLOADED_REFERENCE_UNGAPPED_HAMMING';result.mismatchesAllowed=maxMismatches;result.countIsLowerBound=result.truncated;return {name:a+'/'+b,result};});renderResults();toast('替换扫描已完成；仍需结合配对产物、材料背景和实验复核。');
 }catch(e){if(!cancelRequested)error(e.message);}finally{setBusy(false);}
}
exportCsv=function(selectedOnly=false){selectedOnly=selectedOnly===true;const extra=['review_selection','repeat_status','repeat_policy','locus_gc_pm50_pct','locus_gc_pm250_pct','locus_repeat_pm500_pct','primer_repeat_overlap_bp','primer_repeat_3prime8_overlap_bp','background_status','excluded_intervals','approximate_mismatch_limit','approximate_total_hits','approximate_positions_truncated','thermodynamic_review','imported_review_only','rescue_enabled','rescue_attempts','rescue_selected_max_product','rescue_reason'];const rows=[[...columns,...extra]];
 for(const r of results)for(let i=0;i<r.candidates.length;i++){const c=r.candidates[i];if(selectedOnly&&!c.selected)continue;for(const o of c.primers){const exact=c.exactCheck?.results.find(x=>x.id===o.role),near=c.approxCheck?.results.find(x=>x.id===o.role);
 rows.push([r.context.id,r.mode,i+1,isSyntheticResult(r)?'SYNTHETIC_NOT_FOR_ORDER':c.status,r.reference?.filename,r.reference?.sha256,r.context.templateSha256,(r.context.geneHits||[]).map(g=>g.id).join(';'),compactFeatureLabel(r.context.featureContext||[]),nearestBoundarySummary(r.context.featureContext||[],'nearest_donor_boundary')?.distance_bp??'NA',nearestBoundarySummary(r.context.featureContext||[],'nearest_acceptor_boundary')?.distance_bp??'NA',r.context.spliceMotifAudit?.status||'NOT_RUN',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.variant_overlaps_any_motif?'YES':'NO'):'NOT_ASSESSED',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.noncanonical_nearby?'YES':'NO'):'NOT_ASSESSED',r.context?.annotationAudit?.gff?.filename||r.reference?.gff?.filename||'',r.context?.annotationAudit?.gff?.sha256||r.reference?.gff?.sha256||'',r.context.chrom,r.context.pos,r.context.ref,r.context.alt,o.role,o.allele,o.channel,o.strand,o.core,o.tail,o.sequence,o.length,o.fullLength,fmt(o.tm,4),fmt(o.gc,4),c.productRef,c.productAlt,o.genomicStart1,o.genomicEnd1,o.selfEnd,o.hairpin,exact?.totalHits??'NOT_RUN',RPSAudit.scanEvidence(r,c).status,'NOT_VALIDATED',r.algorithm,r.version,c.selected?'SELECTED_FOR_REVIEW':'NOT_SELECTED',r.inputContext?.repeatAudit?.status||'NOT_PROVIDED',r.inputContext?.repeatAudit?.policy||'annotate',fmt(r.locusDiagnostics?.gcWindows?.pm50?.gc,4),fmt(r.locusDiagnostics?.gcWindows?.pm250?.gc,4),fmt(r.locusDiagnostics?.repeatFraction500,4),o.repeatOverlapBp??'NA',o.repeatOverlap3prime8Bp??'NA',r.inputContext?.backgroundAudit?.status||'NOT_PROVIDED',r.inputContext?.excludedRegions?.length??0,c.approxCheck?.mismatchesAllowed??'NOT_RUN',near?.totalHits??'NOT_RUN',near?.positionsTruncated??'NOT_RUN',c.thermoCheck?'PRIMER3_NUMERICAL_ONLY':'NOT_RUN',r.importedReviewOnly?'YES':'NO',r.rescueAudit?.enabled?'YES':'NO',(r.rescueAudit?.attemptedMaxProducts||[]).join('>'),r.rescueAudit?.selectedMaxProduct??'NA',r.rescueAudit?.reason||'NA']);
 }}save(selectedOnly?'rice_primer_selected_review.csv':'rice_primer_candidates_v1.1.0-rc4.3.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');
};
csvCell=function(v){let s=String(v??'');if(/^[\s\uFEFF]*[=+@\-]/.test(s)||/^[\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
