function exportAmplicons(){const lines=[],selected=selectedCount()>0;for(const r of results)for(let i=0;i<r.candidates.length;i++){const c=r.candidates[i];if(selected&&!c.selected)continue;const a=RPSReview.amplicons(r.inputContext,c);for(const allele of ['ref','alt']){lines.push(`>${String(r.context.id).replace(/[^A-Za-z0-9_.-]/g,'_')}_C${i+1}_${allele.toUpperCase()} source=${r.context.source} status=NOT_VALIDATED includes_tail=false orientation=${a.orientation}`,...a[allele].match(/.{1,80}/g));}}save('rice_amplicons_'+(selected?'selected':'all')+'.fasta',lines.join('\n')+'\n');}
function exportDiagnostics(){const rows=[['target_id','mode','candidate_count','status','error','algorithm','background_status','selected_candidate','imported_review_only']];for(const r of results)rows.push([r.context.id,r.mode,r.candidates.length,r.error?'ERROR':r.candidates.length?'CANDIDATES_UNVALIDATED':'NO_CANDIDATE_AT_CURRENT_SETTINGS',r.error||'',r.algorithm,r.inputContext?.backgroundAudit?.status||'NOT_PROVIDED',r.candidates.findIndex(c=>c.selected)>=0?r.candidates.findIndex(c=>c.selected)+1:'NONE',r.importedReviewOnly?'YES':'NO']);save('rice_primer_diagnostics.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
$('checkBackend').onclick=checkBackend;

$('repeatFile').onchange=async e=>{const f=e.target.files[0];if(!f){repeatRows=[];repeatFileMeta=null;$('repeatMeta').textContent='未载入。';dirty();return;}if(f.size>150*1024*1024){error('重复注释超过 150 MB；建议预先转为仅含 repeat 的 BED。');e.target.value='';return;}try{const text=await f.text();const parsed=parseRepeatText(text,$('repeatFormat').value);repeatRows=parsed.rows;repeatFileMeta={filename:f.name,size:f.size,sha256:await RPSIO.hashFile(f),format:parsed.format,loadedAt:new Date().toISOString()};$('repeatMeta').textContent=`${f.name} · ${repeatRows.length.toLocaleString()} 个区间 · ${parsed.format.toUpperCase()}；尚未证明与当前 FASTA 同源，请以实际局部重叠和坐标来源复核。`;dirty();toast('重复注释已载入。');}catch(err){repeatRows=[];repeatFileMeta=null;e.target.value='';error(err.message);}};
$('repeatFormat').onchange=()=>{if($('repeatFile').files[0]){$('repeatFile').dispatchEvent(new Event('change'));}else dirty();};$('repeatPolicy').onchange=dirty;$('gcRegionHigh').oninput=dirty;$('gcRegionLow').oninput=dirty;$('autoRescue').onchange=dirty;$('rescueTrigger').onchange=dirty;$('rescueMaxProduct').oninput=dirty;$('rescueStep').oninput=dirty;
$('backgroundFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024){error('背景清单超过 20 MB。');return;}const t=await f.text();try{RPSReview.parseBackground(t);$('backgroundText').value=t;$('backgroundAck').checked=false;dirty();toast('背景清单已载入；请确认所有记录均需避让。');}catch(err){error(err.message);}};
$('selectedCsv').onclick=()=>exportCsv(true);$('exportAmplicons').onclick=exportAmplicons;$('exportDiagnostics').onclick=exportDiagnostics;
$('importRun').onchange=async e=>{const f=e.target.files[0];if(!f||busy)return;clearError();try{if(f.size>20*1024*1024)throw Error('运行 JSON 超过 20 MB。');const d=RPSReview.validateImport(JSON.parse(await f.text()));results=d.results;runManifest={...d.manifest,importedAt:new Date().toISOString(),importFileSha256:shaText(await f.text())};$('staleNote').classList.add('hidden');$('importNote').classList.remove('hidden');renderResults();$('results').scrollIntoView({behavior:'smooth'});toast('历史快照已载入，仅供复核；未重算，参考扫描入口保持禁用。');}catch(err){error('载入失败：'+err.message);}finally{e.target.value='';}};

$('toggleRef').onclick=()=>$('reference').classList.toggle('open');
$('gffFile').onchange=ev=>{const f=ev.target.files[0];if(!f)return;gffFile=f;gffIndex=null;gffSha=null;gffAudit=null;gffSelectedGene=null;$('indexGff').disabled=false;$('clearGff').disabled=false;$('geneQuery').disabled=true;$('geneSearch').disabled=true;$('geneResults').classList.add('hidden');$('geneDetail').innerHTML='';updateGffMeta();dirty();};
$('indexGff').onclick=()=>indexGffFile();$('clearGff').onclick=()=>{gffFile=null;gffIndex=null;gffSha=null;gffAudit=null;gffSelectedGene=null;$('gffFile').value='';$('indexGff').disabled=true;$('clearGff').disabled=true;$('geneQuery').disabled=true;$('geneSearch').disabled=true;$('geneResults').classList.add('hidden');$('geneDetail').innerHTML='';updateGffMeta();dirty();};$('geneSearch').onclick=searchGenes;$('geneQuery').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchGenes();}};$('fetchRefBase').onclick=()=>fetchReferenceAtTarget();$('inspectVariantStructure').onclick=inspectCurrentVariantStructure;
$('fastaFile').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{const b=new Uint8Array(await file.slice(0,2).arrayBuffer());if(b[0]===0x1f&&b[1]===0x8b)throw Error('请先将 .gz FASTA 解压；此版本使用未压缩 FASTA 字节索引。');if(b[0]!==62)throw Error('FASTA 应以 > 开头；请移除 BOM，并确认不是索引或表格文件。');refFile=file;entries=[];refSha=null;indexAudit=null;refRevision++;if(gffIndex){gffAudit=null;updateGffMeta();}$('faiFile').value='';renderRef();dirty();if(results.length)renderResults();toast('FASTA 已选择；请载入 FAI，或构建索引。');}catch(e){ev.target.value='';error(e.message);}};
$('faiFile').onchange=async ev=>{const f=ev.target.files[0];if(!f)return;try{if(!refFile)throw Error('请先选择 FASTA，再载入对应 FAI。');const es=RPS.parseFai(await f.text());const checked=await RPSIO.verifyIndexBoundaries(refFile,es);entries=es;indexAudit=checked;refRevision++;renderRef();if(gffIndex){gffAudit=gffMappingAudit();updateGffMeta();}dirty();if(results.length)renderResults();toast('FAI 已载入；完整参考身份仍需核对来源和校验值。');}catch(e){error(e.message);}};
$('buildIndex').onclick=async()=>{if(busy)return;if(!refFile){error('请先选择 FASTA。');return;}clearError();cancelRequested=false;setBusy(true);try{const r=await runWorker('index',{file:refFile},p=>showProgress(`构建索引并计算 SHA-256 · ${(100*p).toFixed(0)}%`,p));entries=r.entries;refSha=r.sha256;indexAudit={method:'STREAMED_BUILD_AND_FULL_SHA256',contigsChecked:entries.length,fullFileHashed:true,identityVerified:false};refRevision++;renderRef();if(gffIndex){gffAudit=gffMappingAudit();updateGffMeta();}dirty();if(results.length)renderResults();toast('索引与文件 SHA-256 已计算。');}catch(e){if(!cancelRequested)error(e.message);}finally{setBusy(false);}};
$('hashRef').onclick=async()=>{if(busy)return;if(!refFile){error('请先选择 FASTA。');return;}cancelRequested=false;clearError();setBusy(true);try{refSha=await runWorker('hash',{file:refFile},p=>showProgress(`计算 FASTA SHA-256 · ${(100*p).toFixed(0)}%`,p));renderRef();dirty();toast('文件 SHA-256 已计算；旧结果仍保留原运行快照。');}catch(e){if(!cancelRequested)error(e.message);}finally{setBusy(false);}};
$('saveFai').onclick=()=>save((refFile?.name||'reference.fa')+'.fai',faiText());
$('cancelJob').onclick=()=>{cancelRequested=true;if(nativeAbort)nativeAbort.abort();if(activeWorker)activeWorker.terminate();const reject=activeReject;activeWorker=null;activeReject=null;if(reject)reject(Error('任务已取消。'));showProgress('正在取消，保留已完成结果。');};
$('batchFile').onchange=async ev=>{const f=ev.target.files[0];if(f){if(f.size>20*1024*1024){error('位点表超过 20 MB，请仅保留本批次目标。');return;}$('batchText').value=await f.text();dirty();}};
$('downloadTemplate').onclick=()=>save('variant_template.tsv','id\tchrom\tpos\tref\talt\n');
$('resetParams').onclick=resetParams;$('runDesign').onclick=runDesign;$('demoSnp').onclick=()=>loadDemo('snp');$('demoDel').onclick=()=>loadDemo('del');
$('exportCsv').onclick=()=>exportCsv(false);$('exportFasta').onclick=exportFasta;$('exportJson').onclick=()=>exportJson();
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>setInput(b.dataset.input));document.querySelectorAll('input:not([type=file]),textarea,select').forEach(e=>e.addEventListener('input',dirty));
// Expose no network API. Everything below is deterministic local state.

// v1.1.0-rc4.3 — evidence-bounded candidate adjudication. Labels are review priority, never wet-lab release.
function decisionEvidence(r,c){
 const repeatProvided=r.inputContext?.repeatAudit?.status==='PROVIDED';
 const bgProvided=r.inputContext?.backgroundAudit?.status&&r.inputContext.backgroundAudit.status!=='NOT_PROVIDED';
 const near=Boolean(c.approxCheck), exact=Boolean(c.exactCheck), thermo=Boolean(c.thermoCheck);
 return {repeatProvided,bgProvided,near,exact,thermo,wetLab:false};
}
function observedSpecificityRisk(c,r){return RPSAudit.scanEvidence(r||{inputContext:{},reference:null},c);}
function candidateFacts(r,c){
 const repeat3=c.primers.reduce((n,o)=>n+(o.repeatOverlap3prime8Bp||0),0),repeatAny=c.primers.reduce((n,o)=>n+(o.repeatOverlapBp||0),0);
 const integrity=RPSAudit.candidateIntegrity(r,c),spec=observedSpecificityRisk(c,r);
 const d=r.locusDiagnostics||{},hi=r.parameters?.regionGcHigh??70,lo=r.parameters?.regionGcLow??25;
 const localGc=Object.values(d.gcWindows||{}).map(x=>x?.gc).filter(Number.isFinite);
 const gcWarn=localGc.some(v=>v>hi||v<lo),kaspIndel=c.mode==='kasp'&&c.variantClass==='INDEL',concerns=[],gaps=[];
 if(integrity.status!=='CONSISTENT')concerns.push('候选一致性失败：'+integrity.errors.join(', '));
 if(repeat3)concerns.push(`3′端 repeat 重叠 ${repeat3} bp`);else if(repeatAny)concerns.push(`引物 repeat 重叠 ${repeatAny} bp`);
 if(spec.risk)concerns.push('参考内额外潜在结合位点：'+spec.detail.join('; '));
 if(spec.errors.length)concerns.push('扫描一致性失败：'+spec.errors.join(', '));
 if(spec.truncated)concerns.push('命中位置截断，配对产物未穷尽');
 if(kaspIndel)concerns.push('KASP InDel 需要独立专家签核，不能自动取得复核资格');
 if(gcWarn)concerns.push('局部 GC 超出本次运行保存的提示线');
 const amps=c.ampliconAudit;
 if([amps?.ref?.peak50?.gc,amps?.alt?.peak50?.gc].some(v=>Number.isFinite(v)&&v>hi))concerns.push('扩增子存在超过提示线的高 GC 50 bp 窗口');
 if(amps?.readReach&&!amps.readReach.oneDirectionWithinPlan)concerns.push('扩增不等于可直接读到目标：需评估内部测序引物');
 const ev=decisionEvidence(r,c);
 if(!ev.repeatProvided)gaps.push('repeat 注释缺失或坐标范围未核验');
 if(!ev.bgProvided)gaps.push('背景变异清单未提供');
 if(spec.status!=='COMPLETE_LIMITED'||spec.source!=='APPROXIMATE')gaps.push('近似扫描尚无完整且匹配的证据：'+spec.gaps.join(', '));
 if(!ev.thermo)gaps.push('Primer3 热力学数值未取得');else gaps.push('热力学仅有数值，不等于接受性检查通过');
 if(c.primers.some(o=>o.repeatProjectionUnknownBp>0))gaps.push('ALT 插入/复杂替换片段无法由 REF repeat 注释完整投影');
 if(Object.values(d.gcWindows||{}).some(w=>w.ambiguousBases>0))gaps.push('区域含 N/IUPAC；GC 分母仅有效碱基，不确定区间未视为正常');
 if(r.importedReviewOnly)gaps.push('历史导入仅回看，不能进入当前复核资格清单');
 gaps.push('实验未验证');
 const hardRisk=(integrity.status!=='CONSISTENT'?1:0)+(repeat3>0?1:0)+(spec.risk>0?1:0)+(spec.errors.length?1:0)+(spec.truncated?1:0)+(kaspIndel?1:0);
 return {repeat3,repeatAny,spec,gcWarn,kaspIndel,concerns,gaps,hardRisk,evidence:ev,integrity};
}
function adjudicateLocus(r){
 if(r.error)return {locusTier:'NO_DESIGN',label:'错误',preferred:null,reason:[r.error],rows:[]};
 if(!r.candidates?.length)return {locusTier:'NO_DESIGN',label:'No design',preferred:null,reason:['当前参数与 Auto-rescue 范围内无候选'],rows:[]};
 const rows=r.candidates.map((c,i)=>({i,c,f:candidateFacts(r,c)}));
 rows.sort((a,b)=>a.f.hardRisk-b.f.hardRisk||a.f.spec.risk-b.f.spec.risk||a.f.repeat3-b.f.repeat3||a.f.repeatAny-b.f.repeatAny||Number(a.c.score)-Number(b.c.score)||a.i-b.i);
 const best=rows[0],allHard=rows.every(x=>x.f.hardRisk>0);
 for(const x of rows){
   let tier;if(x===best&&!allHard)tier='RECOMMENDED_FOR_REVIEW';else if(x.f.hardRisk>0)tier='DIFFICULT_REVIEW';else tier='ALTERNATIVE';
   x.c.reviewDecision={tier,rank:rows.indexOf(x)+1,concerns:x.f.concerns,gaps:x.f.gaps,basis:'LEXICOGRAPHIC_OBSERVED_RISK_THEN_ENGINE_SCORE',wetLab:'NOT_VALIDATED'};
 }
 if(allHard){best.c.reviewDecision.tier='DIFFICULT_REVIEW';return {locusTier:'DIFFICULT_REVIEW',label:'Difficult',preferred:best.i,reason:best.f.concerns.length?best.f.concerns:['所有候选均存在已观察风险'],rows};}
 return {locusTier:'RECOMMENDED_FOR_REVIEW',label:'Recommended',preferred:best.i,reason:best.f.concerns,rows};
}
function decisionBadge(tier){const m={RECOMMENDED_FOR_REVIEW:['recommended','推荐 · 仅复核'],ALTERNATIVE:['alternative','Alternative'],DIFFICULT_REVIEW:['difficult','Difficult'],NO_DESIGN:['none','No design']},x=m[tier]||m.NO_DESIGN;return `<span class="decision-badge ${x[0]}">${x[1]}</span>`;}
function candidateDecisionHTML(r,c){const a=adjudicateLocus(r);const d=c.reviewDecision||{},cls=d.tier==='RECOMMENDED_FOR_REVIEW'?'recommended':d.tier==='DIFFICULT_REVIEW'?'difficult':'alternative';const concerns=d.concerns||[],gaps=d.gaps||[];return `<div class="decision-box ${cls}"><strong>${decisionBadge(d.tier)} · locus 内排序 #${d.rank||'—'}</strong><div class="hint" style="margin-top:5px">${concerns.length?'已观察关注项：'+concerns.map(esc).join('；'):'当前已运行检查中未观察到硬风险。'}${gaps.length?'<br>证据缺口：'+gaps.map(esc).join('；'):''}</div><div class="evidence-row"><span class="evidence-chip ${r.inputContext?.repeatAudit?.status==='PROVIDED'?'done':''}">repeat</span><span class="evidence-chip ${r.inputContext?.backgroundAudit?.status&&r.inputContext.backgroundAudit.status!=='NOT_PROVIDED'?'done':''}">background</span><span class="evidence-chip ${RPSAudit.scanEvidence(r,c).status==='COMPLETE_LIMITED'&&c.approxCheck?'done':''}">near-match</span><span class="evidence-chip ${''}">thermo 未验收</span><span class="evidence-chip">wet-lab</span></div></div>`;}
function decisionDashboardHTML(){
 const ads=results.map(r=>adjudicateLocus(r));const nRec=ads.filter(a=>a.locusTier==='RECOMMENDED_FOR_REVIEW').length,nDiff=ads.filter(a=>a.locusTier==='DIFFICULT_REVIEW').length,nNone=ads.filter(a=>a.locusTier==='NO_DESIGN').length;
 const rows=results.map((r,i)=>{const a=ads[i],pc=a.preferred==null?null:r.candidates[a.preferred],d=pc?.reviewDecision;return `<tr><td>${esc(r.context.id||'target')}</td><td>${decisionBadge(a.locusTier)}</td><td>${pc?'C'+String(a.preferred+1).padStart(2,'0'):'—'}</td><td>${d?.concerns?.length?d.concerns.map(esc).join('；'):'—'}</td><td>${d?.gaps?.length?d.gaps.map(esc).join('；'):'—'}</td><td class="mono">${r.rescueAudit?.selectedMaxProduct??'—'}</td></tr>`;}).join('');
 return `<div class="decision-dashboard"><h3>批量位点裁决面板</h3><div class="hint">这是候选进入人工复核的优先级，不是订购/实验放行。未运行检查明确保留为证据缺口。</div><div class="decision-grid"><div class="decision-stat"><strong>${results.length}</strong><small>已完成位点</small></div><div class="decision-stat"><strong>${nRec}</strong><small>Recommended for review</small></div><div class="decision-stat"><strong>${nDiff}</strong><small>Difficult</small></div><div class="decision-stat"><strong>${nNone}</strong><small>No design / error</small></div></div><div class="table-wrap"><table class="decision-table"><thead><tr><th>位点</th><th>裁决</th><th>首选候选</th><th>已观察关注项</th><th>证据缺口</th><th>搜索上限 bp</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
}
const v04CardHTML=cardHTML;
cardHTML=function(r,c,ri,ci){adjudicateLocus(r);let html=v04CardHTML(r,c,ri,ci);html=html.replace('<div class="metrics">',candidateDecisionHTML(r,c)+'<div class="metrics">');return html;};
const v04RenderResults=renderResults;
renderResults=function(){for(const r of results)adjudicateLocus(r);v04RenderResults();if(results.length){const root=$('resultContent');root.insertAdjacentHTML('afterbegin',decisionDashboardHTML());$('qcWorkbench')?.classList.remove('hidden');}else{$('qcWorkbench')?.classList.add('hidden');}$('exportDecision').disabled=busy||!results.length;$('autoSelectPreferred').disabled=busy||!results.some(r=>r.candidates?.length);bindQc();applyQcFilters();};
function exportDecision(){const rows=[['target_id','mode','locus_decision','preferred_candidate','candidate_count','observed_concerns','evidence_gaps','repeat_status','background_status','near_match_status','thermo_status','wetlab_status','rescue_selected_max_product','reference_sha256','template_sha256','gene_overlap','feature_region','nearest_donor_boundary_bp','nearest_acceptor_boundary_bp','splice_motif_check','splice_motif_overlap','splice_nearby_noncanonical','gff_file','gff_sha256']];for(const r of results){const a=adjudicateLocus(r),c=a.preferred==null?null:r.candidates[a.preferred],d=c?.reviewDecision;rows.push([r.context.id,r.mode,a.locusTier,a.preferred==null?'NONE':a.preferred+1,r.candidates?.length||0,(d?.concerns||a.reason||[]).join('; '),(d?.gaps||[]).join('; '),r.inputContext?.repeatAudit?.status||'NOT_PROVIDED',r.inputContext?.backgroundAudit?.status||'NOT_PROVIDED',c?RPSAudit.scanEvidence(r,c).status:'NOT_RUN',c?.thermoCheck?'NUMERICAL_ONLY_UNACCEPTED':'NOT_RUN','NOT_VALIDATED',r.rescueAudit?.selectedMaxProduct??'NA',r.reference?.sha256||'NA',r.context.templateSha256||'NA',(r.context.geneHits||[]).map(g=>g.id).join(';'),compactFeatureLabel(r.context.featureContext||[]),nearestBoundarySummary(r.context.featureContext||[],'nearest_donor_boundary')?.distance_bp??'NA',nearestBoundarySummary(r.context.featureContext||[],'nearest_acceptor_boundary')?.distance_bp??'NA',r.context.spliceMotifAudit?.status||'NOT_RUN',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.variant_overlaps_any_motif?'YES':'NO'):'NOT_ASSESSED',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.noncanonical_nearby?'YES':'NO'):'NOT_ASSESSED',r.context?.annotationAudit?.gff?.filename||r.reference?.gff?.filename||'NA',r.context?.annotationAudit?.gff?.sha256||r.reference?.gff?.sha256||'NA']);}save('rice_primer_locus_decisions_v1.1.0-rc4.3.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function autoSelectPreferred(){for(const r of results){const a=adjudicateLocus(r);r.candidates.forEach((c,i)=>c.selected=a.preferred===i);}renderResults();toast('已按当前已观察证据选择每个位点首选候选；仅进入复核清单，不是订购批准。');}
$('exportDecision').onclick=exportDecision;$('autoSelectPreferred').onclick=autoSelectPreferred;
// Extend candidate CSV with review decision fields without changing existing schema order.
const v04ExportCsv=exportCsv;
exportCsv=function(selectedOnly=false){for(const r of results)adjudicateLocus(r);selectedOnly=selectedOnly===true;const extra=['review_selection','review_decision','review_rank','review_observed_concerns','review_evidence_gaps','repeat_status','repeat_policy','locus_gc_pm50_pct','locus_gc_pm250_pct','locus_repeat_pm500_pct','primer_repeat_overlap_bp','primer_repeat_3prime8_overlap_bp','background_status','excluded_intervals','approximate_mismatch_limit','approximate_total_hits','approximate_positions_truncated','thermodynamic_review','imported_review_only','rescue_enabled','rescue_attempts','rescue_selected_max_product','rescue_reason'];const rows=[[...columns,...extra]];
 for(const r of results)for(let i=0;i<r.candidates.length;i++){const c=r.candidates[i];if(selectedOnly&&!c.selected)continue;for(const o of c.primers){const exact=c.exactCheck?.results.find(x=>x.id===o.role),near=c.approxCheck?.results.find(x=>x.id===o.role),d=c.reviewDecision||{};rows.push([r.context.id,r.mode,i+1,isSyntheticResult(r)?'SYNTHETIC_NOT_FOR_ORDER':c.status,r.reference?.filename,r.reference?.sha256,r.context.templateSha256,(r.context.geneHits||[]).map(g=>g.id).join(';'),compactFeatureLabel(r.context.featureContext||[]),nearestBoundarySummary(r.context.featureContext||[],'nearest_donor_boundary')?.distance_bp??'NA',nearestBoundarySummary(r.context.featureContext||[],'nearest_acceptor_boundary')?.distance_bp??'NA',r.context.spliceMotifAudit?.status||'NOT_RUN',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.variant_overlaps_any_motif?'YES':'NO'):'NOT_ASSESSED',r.context.spliceMotifAudit?.status==='PERFORMED_LOCAL_FASTA'?(r.context.spliceMotifAudit.noncanonical_nearby?'YES':'NO'):'NOT_ASSESSED',r.context?.annotationAudit?.gff?.filename||r.reference?.gff?.filename||'',r.context?.annotationAudit?.gff?.sha256||r.reference?.gff?.sha256||'',r.context.chrom,r.context.pos,r.context.ref,r.context.alt,o.role,o.allele,o.channel,o.strand,o.core,o.tail,o.sequence,o.length,o.fullLength,fmt(o.tm,4),fmt(o.gc,4),c.productRef,c.productAlt,o.genomicStart1,o.genomicEnd1,o.selfEnd,o.hairpin,exact?.totalHits??'NOT_RUN',RPSAudit.scanEvidence(r,c).status,'NOT_VALIDATED',r.algorithm,r.version,c.selected?'SELECTED_FOR_REVIEW':'NOT_SELECTED',d.tier||'UNRANKED',d.rank??'NA',(d.concerns||[]).join('; '),(d.gaps||[]).join('; '),r.inputContext?.repeatAudit?.status||'NOT_PROVIDED',r.inputContext?.repeatAudit?.policy||'annotate',fmt(r.locusDiagnostics?.gcWindows?.pm50?.gc,4),fmt(r.locusDiagnostics?.gcWindows?.pm250?.gc,4),fmt(r.locusDiagnostics?.repeatFraction500,4),o.repeatOverlapBp??'NA',o.repeatOverlap3prime8Bp??'NA',r.inputContext?.backgroundAudit?.status||'NOT_PROVIDED',r.inputContext?.excludedRegions?.length??0,c.approxCheck?.mismatchesAllowed??'NOT_RUN',near?.totalHits??'NOT_RUN',near?.positionsTruncated??'NOT_RUN',c.thermoCheck?'PRIMER3_NUMERICAL_ONLY':'NOT_RUN',r.importedReviewOnly?'YES':'NO',r.rescueAudit?.enabled?'YES':'NO',(r.rescueAudit?.attemptedMaxProducts||[]).join('>'),r.rescueAudit?.selectedMaxProduct??'NA',r.rescueAudit?.reason||'NA']);}}
 save(selectedOnly?'rice_primer_selected_review_v1.1.0-rc4.3.csv':'rice_primer_candidates_v1.1.0-rc4.3.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');};

function qcCandidateFor(r){const a=adjudicateLocus(r);if(a.preferred==null)return null;const selected=r.candidates?.find(c=>c.selected);return selected||r.candidates[a.preferred]||null;}
function qcGapFlags(r,c){const scan=c?RPSAudit.scanEvidence(r,c):null;return {near:scan?.status!=='COMPLETE_LIMITED'||scan?.source!=='APPROXIMATE',repeat:r.inputContext?.repeatAudit?.status!=='PROVIDED',background:!(r.inputContext?.backgroundAudit?.status&&r.inputContext.backgroundAudit.status!=='NOT_PROVIDED'),thermo:true};}
