function variantStructureHTML(context,fc){if(!fc?.length)return `<div class="notice amber">当前 REF 区间未与已索引 GFF3 的 gene 重叠，或 contig 无法映射。不能据此断言 intergenic；请同时核对 GFF3 完整性与坐标体系。</div>`;const donor=nearestBoundarySummary(fc,'nearest_donor_boundary'),acceptor=nearestBoundarySummary(fc,'nearest_acceptor_boundary');const regs=[...new Set(fc.flatMap(g=>g.transcripts.map(t=>t.region)))].join(' / ');return `${variantStructureSvg(context,fc)}<div class="feature-summary"><div class="feature-box"><strong>${esc(compactFeatureLabel(fc))}</strong><small>gene / region overlap</small></div><div class="feature-box"><strong>${esc(regs)}</strong><small>transcript genomic region</small></div><div class="feature-box"><strong>${donor?donor.distance_bp+' bp':'NA'}</strong><small>最近 donor exon boundary</small></div><div class="feature-box"><strong>${acceptor?acceptor.distance_bp+' bp':'NA'}</strong><small>最近 acceptor exon boundary</small></div></div><div class="hint" style="margin-top:8px">donor / acceptor 按 transcript strand 与 exon 顺序定义边界；distance=0 表示 REF 区间覆盖该边界。</div>${spliceAuditHTML(context.spliceMotifAudit)}<div class="hint" style="margin-top:8px">即使 REF motif 为 canonical 且变异覆盖它，也这里只报告结构/序列事实，不自动赋予 splice_donor_variant、splice_acceptor_variant 或功能丧失结论。</div>`;}
async function inspectCurrentVariantStructure(){clearError();try{const v=singleVariant();if(!gffIndex)throw Error('请先加载并索引 GFF3。');if(!refFile||!entries.length)throw Error('请先加载 FASTA 与 FAI，剪接序列检查需要参考序列。');const e=RPS.resolveContig(entries,v.chrom);const c={...v,chrom:e.name,source:'LOCAL_REFERENCE'};const fc=targetFeatureContext(c);c.spliceMotifAudit=await spliceMotifAudit(c,fc,20);$('variantStructurePreview').innerHTML=variantStructureHTML(c,fc);}catch(e){error(e.message);}}
function targetGeneHits(context){if(!gffIndex||!context?.chrom||!Number.isInteger(context.pos))return [];const end=context.pos+Math.max(1,(context.ref||'').length)-1;return RPSGFF.overlapGenes(gffIndex,context.chrom,context.pos,end,n=>RPS.resolveContig(entries,n).name).slice(0,20).map(g=>({id:g.id||g.name,seqid:g.seqid,start:g.start,end:g.end,strand:g.strand}));}
async function genomicContext(v,p){if(!refFile||!entries.length)throw Error('请先配置本地 MSU FASTA 与 FAI 索引。');const e=RPS.resolveContig(entries,v.chrom);if(v.pos+v.ref.length-1>e.length)throw Error('目标区间超出染色体长度。');const pad=p.maxProduct+100,st=Math.max(0,v.pos-1-pad),en=Math.min(e.length,v.pos-1+v.ref.length+pad),seq=await RPS.fetchSeq(refFile,e,st,en);return {...v,chrom:e.name,seq,target0:v.pos-1-st,start1:st+1,source:'LOCAL_REFERENCE'};}
function singleVariant(){const id=$('targetId').value.trim()||'target_001',chrom=$('chrom').value.trim(),pos=Number($('pos').value),ref=$('ref').value.trim().toUpperCase(),alt=$('alt').value.trim().toUpperCase();if(!chrom||!Number.isSafeInteger(pos)||pos<1)throw Error('请输入染色体与有效的 1-based POS。');if(!/^[ACGT]+$/.test(ref)||!/^[ACGT]+$/.test(alt)||ref===alt)throw Error('请提供不同的 REF / ALT 序列等位。');return {id,chrom,pos,ref,alt};}

function parseRepeatText(text,format='auto'){
 const lines=text.split(/\r?\n/),out=[];let detected=format;
 for(const raw of lines){const line=raw.trim();if(!line||line.startsWith('#')||/^(track |browser )/.test(line))continue;const f=line.split('\t');if(/^(chrom|chromosome|seqid)$/i.test(f[0])&&/start/i.test(f[1]||''))continue;
  if(detected==='auto'){if(f.length>=9 && /^\d+$/.test(f[3]||'') && /^\d+$/.test(f[4]||''))detected='gff';else detected='bed';}
  let chrom,start0,end0,label='repeat';
  if(detected==='gff'){if(f.length<9)throw Error('repeat GFF3 不足 9 列');chrom=f[0];const a=Number(f[3]),b=Number(f[4]);if(!Number.isSafeInteger(a)||!Number.isSafeInteger(b)||a<1||b<a)throw Error('repeat 坐标无效：'+line);start0=a-1;end0=b;label=f[2]||'repeat';}
  else if(detected==='tsv1'){if(f.length<3)throw Error('repeat 区间不足 3 列');chrom=f[0];const a=Number(f[1]),b=Number(f[2]);if(!Number.isSafeInteger(a)||!Number.isSafeInteger(b)||a<1||b<a)throw Error('repeat 坐标无效：'+line);start0=a-1;end0=b;label=f[3]||'repeat';}
  else {if(f.length<3)throw Error('repeat 区间不足 3 列');chrom=f[0];start0=Number(f[1]);end0=Number(f[2]);if(!Number.isSafeInteger(start0)||!Number.isSafeInteger(end0)||start0<0||end0<=start0)throw Error('repeat BED 坐标无效：'+line);label=f[3]||'repeat';}
  out.push({chrom,start0,end0,label});if(out.length>2500000)throw Error('重复注释超过 250 万条，浏览器版不继续载入。');
 }
 if(!out.length)throw Error('未从重复注释中解析到有效区间。请核对 BED/GFF3/TSV 坐标格式。');
 return {rows:out,format:detected};
}
function repeatForContext(c,rows){
 if(!c.chrom||c.start1==null||!rows.length)return [];
 const st0=c.start1-1,en0=st0+c.seq.length,out=[];
 for(const r of rows){let chrom;try{chrom=RPS.resolveContig(entries,r.chrom).name;}catch{continue;}
  if(chrom===c.chrom&&r.start0<en0&&r.end0>st0)out.push({start0:Math.max(0,r.start0-st0),end0:Math.min(c.seq.length,r.end0-st0),label:r.label,genomicStart0:r.start0,genomicEnd0:r.end0});
 }return out;
}
function applyRepeat(c,rows,policy){
 const mapped=c.chrom&&Number.isSafeInteger(c.start1)&&entries.length;
 let status=!rows.length?'NOT_PROVIDED':!mapped?'NOT_APPLICABLE_UNLOCATED_SEQUENCE':'PROVIDED';
 const bad=new Set();let matchingContig=false;
 if(mapped)for(const r of rows){try{const e=RPS.resolveContig(entries,r.chrom);if(r.end0>e.length)bad.add(r.chrom+':OUT_OF_RANGE');if(e.name===c.chrom)matchingContig=true;}catch{bad.add(r.chrom);}}
 if(status==='PROVIDED'&&(bad.size||!matchingContig))status='COORDINATE_SCOPE_UNRESOLVED';
 const rr=mapped?repeatForContext(c,rows):[];
 const x={...c,repeatRegions:RPSAudit.intervalUnion(rr),repeatAudit:{status,policy,localIntervals:rr.length,unionIntervals:RPSAudit.intervalUnion(rr).length,source:repeatFileMeta,unmappedOrInvalid:[...bad].slice(0,50),targetContigRepresented:matchingContig}};
 if(policy==='exclude'&&status==='COORDINATE_SCOPE_UNRESOLVED')throw Error('repeat 坐标范围尚未核对，不能执行硬排除；请核对 contig、长度和注释覆盖范围。');
 if(policy==='exclude'&&rr.length)x.excludedRegions=[...(x.excludedRegions||[]),...x.repeatRegions.map(r=>({...r,reason:'repeat'}))];
 return x;
}
function gcPct(seq){seq=seq.toUpperCase();let gc=0,n=0;for(const b of seq){if('ACGT'.includes(b)){n++;if(b==='G'||b==='C')gc++;}}return n?100*gc/n:null;}
function maxRun(seq){return RPSAudit.sequenceStats(seq).maxHomopolymer;}
function entropy2(seq){return RPSAudit.sequenceStats(seq).dinucleotideEntropy;}
function overlapBases(a0,a1,regions){return RPSAudit.overlapBp(a0,a1,regions);}
function locusDiagnostics(c){
 const windows={};for(const rad of [50,100,250,500]){const st=Math.max(0,c.target0-rad),en=Math.min(c.seq.length,c.target0+c.ref.length+rad);windows['pm'+rad]={...RPSAudit.sequenceStats(c.seq.slice(st,en)),start0:st,end0:en,requestedLength:c.ref.length+2*rad,clipped:en-st<c.ref.length+2*rad};}
 const st=Math.max(0,c.target0-500),en=Math.min(c.seq.length,c.target0+c.ref.length+500),rep=overlapBases(st,en,c.repeatRegions||[]),stats=RPSAudit.sequenceStats(c.seq.slice(st,en));
 const supplied=c.repeatAudit?.status==='PROVIDED';
 return {gcWindows:windows,repeatFraction500:supplied?100*rep/(en-st):null,repeatBases500:supplied?rep:null,homopolymerMax500:stats.maxHomopolymer,dinucleotideEntropy500:stats.dinucleotideEntropy,knownFraction500:stats.knownFraction,repeatStatus:c.repeatAudit?.status||'NOT_PROVIDED',repeatPolicy:c.repeatAudit?.policy||'annotate'};
}
function annotateCandidate(cand,c){
 for(const o of cand.primers)Object.assign(o,RPSAudit.repeatMetrics(c,o,cand));
 cand.repeatOverlapBp=cand.primers.reduce((n,o)=>n+(o.repeatOverlapBp||0),0);
 cand.ampliconAudit=RPSAudit.ampliconAudit(c,cand,Number($('sangerMaxReadSpan')?.value||700));
 return cand;
}
function locusQualityHTML(r){const d=r.locusDiagnostics;if(!d)return '';const hi=r.parameters?.regionGcHigh??70,lo=r.parameters?.regionGcLow??25;const w=d.gcWindows||{};const cls=v=>v==null?'':v>hi||v<lo?'risk-high':'risk-low';const rep=d.repeatStatus==='PROVIDED'?fmt(d.repeatFraction500,1)+'%':'未提供';return `<div class="locus-quality"><div class="locus-quality-head"><strong>位点难度诊断</strong><span class="hint">描述性指标 · 非实验放行</span></div><div class="locus-quality-grid"><div class="lq"><strong class="${cls(w.pm50?.gc)}">${fmt(w.pm50?.gc,1)}%</strong><small>目标 ±50 bp GC</small></div><div class="lq"><strong class="${cls(w.pm250?.gc)}">${fmt(w.pm250?.gc,1)}%</strong><small>目标 ±250 bp GC</small></div><div class="lq"><strong>${rep}</strong><small>±500 bp repeat fraction</small></div><div class="lq"><strong>${d.homopolymerMax500} bp</strong><small>±500 bp 最大同聚 run</small></div></div><div class="hint" style="margin-top:8px">±100 bp GC ${fmt(w.pm100?.gc,1)}%；±500 bp GC ${fmt(w.pm500?.gc,1)}%；二核苷酸 Shannon entropy ${fmt(d.dinucleotideEntropy500,2)} / 4。有效 A/C/G/T 覆盖率 ${fmt((d.knownFraction500??0)*100,1)}%；窗口被染色体或输入边缘截断时，指标只描述实际可读范围。Repeat=${d.repeatStatus==='PROVIDED'?'已提供注释，策略 '+esc(d.repeatPolicy):'未提供注释，不能据此判断重复风险'}。</div></div>`;}
function rescueSettings(p){const enabled=$('autoRescue').checked,trigger=$('rescueTrigger').value;let ceiling=Number($('rescueMaxProduct').value),step=Number($('rescueStep').value);if(!Number.isSafeInteger(ceiling)||!Number.isSafeInteger(step)||step<10)throw Error('Auto-rescue 最大产物与步长必须为整数，步长至少 10 bp。');const hardMax=mode==='kasp'?500:3000;if(ceiling<p.maxProduct)ceiling=p.maxProduct;if(ceiling>hardMax)throw Error(`当前模式 Auto-rescue 最大产物不能超过 ${hardMax} bp。`);return {enabled,trigger,ceiling,step};}
function repeatBurdenCandidate(c){return (c.primers||[]).reduce((n,o)=>n+(o.repeatOverlapBp||0),0);}
function chooseRescueResult(attempts){const viable=attempts.filter(a=>a.r.candidates?.length);if(!viable.length)return attempts.at(-1);return viable.slice().sort((a,b)=>{const ar=Math.min(...a.r.candidates.map(repeatBurdenCandidate)),br=Math.min(...b.r.candidates.map(repeatBurdenCandidate));return ar-br||a.maxProduct-b.maxProduct||a.r.candidates[0].score-b.r.candidates[0].score;})[0];}
async function designOneWithRescue(item,sourceMode,p,snapshotMode,snapshotEngine,snapshotRef,revision,rs){const attempts=[];const blocked=rs.enabled&&sourceMode!=='sequence'&&Boolean(maskText.trim());let max=p.maxProduct;while(true){const ap={...p,maxProduct:max};const raw=sourceMode==='sequence'?item:await genomicContext(item,ap);let c=RPSReview.applyExclusions(raw,bgRows,maskText);c=applyRepeat(c,repeatRows,$('repeatPolicy').value);if(cancelRequested)throw Error('CANCELLED');const r=await designWithEngine(c,snapshotMode,ap,snapshotEngine);r.locusDiagnostics=locusDiagnostics(c);for(const cand of r.candidates||[])annotateCandidate(cand,c);attempts.push({maxProduct:max,r,c});const has=Boolean(r.candidates?.length),allRepeat=has&&repeatRows.length&&r.candidates.every(x=>repeatBurdenCandidate(x)>0);let retry=rs.enabled&&!blocked&&max<rs.ceiling&&!has;if(rs.enabled&&!blocked&&rs.trigger==='repeat'&&allRepeat&&max<rs.ceiling)retry=true;if(!retry)break;max=Math.min(rs.ceiling,max+rs.step);if(attempts.some(a=>a.maxProduct===max))break;}const best=chooseRescueResult(attempts),r=best.r,c=best.c,expanded=attempts.length>1;let reason='INITIAL_RANGE_ACCEPTED';if(blocked)reason='DISABLED_LOCAL_MANUAL_INTERVALS';else if(expanded&&best.maxProduct>p.maxProduct)reason='EXPANDED_RESULT_SELECTED';else if(expanded)reason='EXPANDED_ATTEMPTS_NOT_SELECTED';else if(rs.enabled&&best.maxProduct>=rs.ceiling&&!r.candidates?.length)reason='CEILING_REACHED_NO_CANDIDATE';r.rescueAudit={enabled:rs.enabled&&!blocked,requestedEnabled:rs.enabled,trigger:rs.trigger,initialMaxProduct:p.maxProduct,ceiling:rs.ceiling,step:rs.step,attemptedMaxProducts:attempts.map(a=>a.maxProduct),selectedMaxProduct:best.maxProduct,expanded,reason,manualLocalIntervalBlocked:blocked,attemptSummaries:attempts.map(a=>({maxProduct:a.maxProduct,candidates:a.r.candidates?.length||0,minRepeatOverlapBp:a.r.candidates?.length?Math.min(...a.r.candidates.map(repeatBurdenCandidate)):null}))};if(expanded)r.warnings=[...(r.warnings||[]),`Auto-rescue 尝试的产物上限：${attempts.map(a=>a.maxProduct).join(' → ')} bp；最终保留 ${best.maxProduct} bp 这一轮。未放宽 Tm、GC、结构或 repeat 硬排除条件。`];if(blocked)r.warnings=[...(r.warnings||[]),'检测到坐标模式的局部模板手工排除区间；为避免窗口扩展改变其含义，本位点未执行 Auto-rescue。'];const annotatedContext={...r.context,templateSha256:shaText(c.seq)};if(sourceMode!=='sequence'&&gffIndex){annotatedContext.geneHits=targetGeneHits(annotatedContext);annotatedContext.featureContext=targetFeatureContext(annotatedContext);annotatedContext.annotationAudit={gff:gffFile?{filename:gffFile.name,sha256:gffSha}:null,mapping:gffAudit};}return {...r,inputContext:c,context:annotatedContext,reference:sourceMode==='sequence'?null:snapshotRef,refRevision:revision,checks:{approximateOffTarget:'NOT_RUN',wetLab:'NOT_VALIDATED'}};}
async function runDesign(){if(busy)return;clearError();cancelRequested=false;let p,items,rs;try{p=params();rs=rescueSettings(p);bgRows=RPSReview.parseBackground($('backgroundText').value);maskText=$('excludedText').value;if(bgRows.length&&entries.length)bgRows=bgRows.map(v=>({...v,resolvedChrom:RPS.resolveContig(entries,v.chrom).name}));if(bgRows.length&&!$('backgroundAck').checked)throw Error('请先确认背景清单的坐标体系及所有记录均需避让。');if($('designEngine').value==='native'&&!nativeInfo?.primer3Available)throw Error('本机 Primer3 尚未就绪，请先检查本机引擎。不会自动回退离线计算。');if(inputMode==='single')items=[singleVariant()];else if(inputMode==='batch')items=RPS.parseDelimited($('batchText').value);else{const c=RPS.parseBracket($('sequenceText').value,demoInfo?demoInfo.id:($('targetId').value||'sequence_target'));if(c.seq.length>20000)throw Error('侧翼序列模式最多 20,000 nt。');if(demoInfo)c.source='SYNTHETIC_DEMO_NOT_MSU';items=[c];}if(inputMode!=='sequence'&&(!refFile||!entries.length))throw Error('请先选择本地参考 FASTA，并加载或构建 FAI 索引。');}catch(e){error(e.message);return;}
 setBusy(true);const snapshotMode=mode,snapshotEngine=$('designEngine').value,sourceMode=inputMode,snapshotRef=refMeta(),revision=refRevision;results=[];runManifest={appVersion:RPS.VERSION,distribution:globalThis.RPSDeployment?.snapshot()||null,algorithm:snapshotEngine==='offline'?'RPS_ENUMERATION_NN_v1':'NATIVE_ADAPTER',engineChoice:snapshotEngine,nativeInfo:snapshotEngine==='native'?nativeInfo:null,backgroundInput:{text:$('backgroundText').value,sha256:shaText($('backgroundText').value),records:bgRows.length,allRecordsAcknowledged:$('backgroundAck').checked},manualExclusions:maskText,repeatAnnotation:{...repeatFileMeta,records:repeatRows.length,policy:$('repeatPolicy').value},geneAnnotation:gffFile?{filename:gffFile.name,size:gffFile.size,sha256:gffSha,indexedGenes:gffIndex?.stats?.genes??null,mappingAudit:gffAudit}:null,startedAt:new Date().toISOString(),inputMode:sourceMode,reference:sourceMode==='sequence'?null:snapshotRef,parameters:p,autoRescue:rs,sources:['https://rice.uga.edu/download_osa1r7.shtml','https://www.biosearchtech.com/how-does-kasp-work','https://biopython.org/docs/latest/api/Bio.SeqUtils.MeltingTemp.html'],validation:{approximateOffTarget:'NOT_RUN',thermodynamicDimerDeltaG:snapshotEngine==='native'?'PER_CANDIDATE_RECORD':'NOT_RUN',parentalVariants:bgRows.length?'PROVIDED_LIST_ONLY':'NOT_PROVIDED',wetLab:'NOT_VALIDATED'}};
 $('staleNote').classList.add('hidden');$('importNote').classList.add('hidden');
 try{for(let i=0;i<items.length;i++){if(cancelRequested)break;showProgress(`正在设计 ${i+1} / ${items.length} · ${items[i].id}`,i/items.length);try{const out=await designOneWithRescue(items[i],sourceMode,p,snapshotMode,snapshotEngine,snapshotRef,revision,rs);if(cancelRequested)break;if(out?.context?.featureContext?.length&&out.context.source==='LOCAL_REFERENCE')out.context.spliceMotifAudit=await spliceMotifAudit(out.context,out.context.featureContext,20);results.push(out);}catch(e){if(cancelRequested||e.message==='CANCELLED')break;results.push({error:e.message,context:items[i],mode:snapshotMode,refRevision:revision,candidates:[]});}renderResults();}
 runManifest.completedAt=new Date().toISOString();runManifest.cancelled=cancelRequested;showProgress(cancelRequested?'已取消，已完成的位点结果仍保留。':'候选计算完成。',1);renderResults();if(!cancelRequested)$('results').scrollIntoView({behavior:'smooth',block:'start'});else toast('已取消；导出文件会保留 cancelled 状态。');}
 catch(e){error(e.message);}finally{setBusy(false);}
}
function schematic(r,c){const mapped=c.primers.filter(o=>o.start0!==null),lo=Math.min(...mapped.map(x=>x.start0)),hi=Math.max(...mapped.map(x=>x.end0)),scale=x=>34+(x-lo)/Math.max(1,hi-lo)*532;let inner='<line x1="34" y1="32" x2="566" y2="32" stroke="#acbcaf" stroke-width="2"/>';
 const p0=r.inputContext.target0,px=scale(p0);if(px>=25&&px<=575)inner+=`<line x1="${px}" y1="12" x2="${px}" y2="49" stroke="#bc833c" stroke-width="2"/><text x="${px}" y="62" text-anchor="middle" fill="#976523" font-size="10">REF/ALT</text>`;
 for(const o of mapped){const x=scale(o.start0),y=scale(o.end0),length=Math.max(14,y-x),x1=o.strand==='+'?x:x+length,x2=o.strand==='+'?x+length:x;inner+=`<line x1="${x1}" y1="32" x2="${x2}" y2="32" stroke="#367b59" stroke-width="5"/><polygon points="${x2},32 ${x2+(o.strand==='+'?-7:7)},26 ${x2+(o.strand==='+'?-7:7)},38" fill="#367b59"/><text x="${(x1+x2)/2}" y="18" text-anchor="middle" fill="#43684e" font-size="10">${esc(o.role)}</text>`;}
 const st=r.inputContext.start1;return `<div class="schematic"><svg viewBox="0 0 600 72" role="img" aria-label="参考等位上的引物方向与变异位置示意">${inner}</svg><div class="hint" style="padding-bottom:7px">${st!=null?esc(r.context.chrom)+':'+(st+lo)+'–'+(st+hi-1):'局部参考窗口 '+lo+'–'+hi+'（0-based）'} · ${c.mode==='kasp'?'仅画 REF 结合区；ALT 不强行投影':'箭头表示引物延伸方向'}</div></div>`;}
function rescueHTML(r){const a=r.rescueAudit;if(!a)return '';const attempted=(a.attemptedMaxProducts||[]).join(' → ');const expanded=a.expanded?`<span class="pill green">Auto-rescue ${esc(a.selectedMaxProduct)} bp</span>`:`<span class="pill">初始范围</span>`;return `<div class="notice" style="margin:10px 0"><strong>搜索范围：</strong> ${expanded}<div class="hint">尝试的产物上限 ${esc(attempted)} bp；初始 ${a.initialMaxProduct} bp，允许上限 ${a.ceiling} bp。${a.manualLocalIntervalBlocked?' 因局部手工排除坐标存在，本位点未扩展。':''} 这里只扩大搜索范围，不放宽引物质量条件。</div></div>`;}
function primerTable(c){return `<div class="table-wrap"><table><thead><tr><th>引物 / 5′ → 3′</th><th>完整序列 <span class="hint">紫色为尾序</span></th><th>Tm / °C</th><th>GC / %</th><th>长度</th></tr></thead><tbody>${c.primers.map(o=>`<tr><td><span class="role ${o.channel==='FAM'?'fam':o.channel==='HEX'?'hex':''}">${esc(o.role)}</span><div class="hint">${o.channel||'PCR'} · ${o.strand}</div></td><td class="seq"><span class="tail">${esc(o.tail)}</span><span class="core">${esc(o.core.slice(0,-1))}<span class="terminal">${esc(o.core.at(-1))}</span></span><div class="hint">${o.genomicStart1!=null?o.genomicStart1+'–'+o.genomicEnd1:o.role==='AS_ALT'?'ALT 构建单倍型':'局部序列'} · 3′自互补 ${o.selfEnd} · 发卡茎 ${o.hairpin}${o.repeatOverlapBp!=null?` · repeat <span class="repeat-overlap">${o.repeatOverlapBp} bp</span>${o.repeatOverlap3prime8Bp?` · 3′8nt ${o.repeatOverlap3prime8Bp} bp`:''}`:''}</div></td><td class="mono">${o.tm.toFixed(2)}</td><td class="mono">${o.gc.toFixed(1)}</td><td class="mono">${o.length}${o.tail?'/'+o.fullLength:''}<div class="hint">${o.tail?'结合区/全长':'nt'}</div></td></tr>`).join('')}</tbody></table></div>`;}
function cardHTML(r,c,ri,ci){const demo=r.context.source?.includes('SYNTHETIC'),scanAllowed=refFile&&r.refRevision===refRevision&&r.context.source==='LOCAL_REFERENCE';return `<article class="result-card"><div class="card-top"><div><strong>候选 ${String(ci+1).padStart(2,'0')}</strong><span class="smallmeta"> · ${c.mode==='sanger'?'Sanger PCR':(c.direction==='+'?'KASP 正向':'KASP 反向')}</span></div><span class="pill amber">${demo?'合成示例 · 禁止订购':c.variantClass==='INDEL'?'InDel · 需专家复核':'未验证候选'}</span></div><div class="card-inner"><div class="metrics"><div class="metric"><span>${c.productRef} / ${c.productAlt}</span><small>REF / ALT 产物 bp${c.mode==='kasp'?' · 不含尾序':''}</small></div>${c.mode==='sanger'?`<div class="metric"><span>${c.readDistanceF} / ${c.readDistanceR}</span><small>F / R 的 3′ 端至目标间隔 bp</small></div>`:`<div class="metric"><span>${esc(c.primers[0].channel)} / ${esc(c.primers[1].channel)}</span><small>REF / ALT 通道绑定</small></div>`}<div class="metric"><span>${c.crossEnd}</span><small>最大连续 3′ 交叉互补 nt</small></div></div>${schematic(r,c)}${primerTable(c)}<div class="result-note">候选排序分数 ${c.score.toFixed(3)}（越低越优先审阅，不是成功率）。${c.mode==='kasp'?'全长序列包含尾序；Tm 和 GC 仅对应结合区。':''}</div><div id="scan-${ri}-${ci}" class="scan-result">${c.exactCheck?scanHTML(c):''}</div></div><div class="card-actions"><button class="btn small" data-copy="${ci}" data-row="${ri}">复制本组序列</button><button class="btn small" data-scan="${ci}" data-row="${ri}" ${!scanAllowed||busy?'disabled':''}>${c.exactCheck?'重新':'进行'}全基因组精确匹配</button><span class="hint">${scanAllowed?'双链 · 零错配 · 不含尾序':'需本次设计所用的本地参考'}</span></div></article>`;}
